#ifndef DEFS_H
#define DEFS_H

#define WINDOW_TITLE ("algolens")

#define WINDOW_HEIGHT 720
#define WINDOW_WIDTH 1280
#define CELL_SIZE 25

#define ALGO_WINDOW_HEIGHT
#define ALGO_WINDOW_WIDTH

#define NUMBER_OF_CELLS_R 40
#define NUMBER_OF_CELLS_C 25
#define NUMBER_OF_CELLS (NUMBER_OF_CELLS_R * NUMBER_OF_CELLS_C)

#define CELL_HEIGHT (ALGO_WINDOW_HEIGHT / NUMBER_OF_CELLS_R)
#define CELL_WIDTH (ALGO_WINDOW_WIDTH / NUMBER_OF_CELLS_C)

#endif
